config/routes.rb
Rails.application.routes.draw do
  resources :comments

  root 'questions#index'

  resources :questions do
    resources :answers, only: [:new, :create]
    resources :comments, only: [:index, :new, :create]
  end
  resources :answers, only: [:index, :show, :edit, :update, :destroy] do
    resources :comments, only: [:index, :new, :create]
  end

  get '/users' => 'users#index'
  get '/signup' => 'users#new'
  get '/users/:id', :to => 'users#show', :as => :user
  get '/login' => 'users#login'

  post '/login' => 'sessions#login'
  post '/signup' => 'sessions#signup'
  delete '/logout' => 'sessions#logout'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  has_many :comments, :as => :commentable
  belongs_to :question
  belongs_to :user
  validates :content, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, :polymorphic => true
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :comments, :as => :commentable
  belongs_to :user
  has_many :answers
  has_many :taggings
  has_many :tags, through: :taggings

  validates :title, presence: true
  validates :content, presence: true

  def all_tags=(names)
    self.tags = names.split(",").map do |name|
      Tag.where(name: name.strip).first_or_create!
    end
  end

  def all_tags
    self.tags.map(&:name).join(", ")
  end

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :posts, through: :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :question
  belongs_to :tag
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :answers
	has_many :answered_questions, through: :answers, source: :question
	has_many :questions

	validates_uniqueness_of :email

	def password
		BCrypt::Password.new(self.hashed_password)
	end

	def password=(user_input)
		self.hashed_password = BCrypt::Password.create(user_input)
	end

	def self.authenticate(email, password)
		user = User.find_by(email: email)
		user if user && user.password == password
	end

	def full_name
    "#{first_name} #{last_name}"
  end

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  
  def index
    @answers = Answer.all
  end

  def new
    question = Question.find_by(id: params[:question_id])
    @answer = Answer.new
  end

  def create
    question = Question.find(params[:question_id])
    answer = Answer.create(answer_params)
    answer.user = current_user
    answer.question = question
    question.answers << answer
    redirect_to question_path(question)
  end

  def show
    @answer = Answer.find(params[:id])
  end

  def edit
    @answer = Answer.find(params[:id])
  end

  def update
    answer = Answer.find(params[:id])
    answer.update_attributes(answer_params)
    redirect_to question_path(answer.question)
  end

  def destroy
    question = Question.find(params[:question_id])
    answer = Answer.find(params[:id])
    answer.destroy
    redirect_to question_path(question)
  end

  def answer_params
    params.require(:answer).permit(:content)
  end  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :set_user_even_if_logged_out

  def set_user_even_if_logged_out
    @user = current_user|| User.new
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user
  end

  helper_method :current_user, :logged_in?
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  def index
    @commentable = find_commentable
    @comments = @commentable.comments
  end

  def new
    @commentable = find_commentable
    @comment = Comment.new
  end


  def create
    @commentable = find_commentable
    @comment = @commentable.comments.create(comment_params)
    if @comment
      redirect_to :id => nil
    else
      render :action => 'new'
    end

  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:content, :commentable_id, :commentable_type)
    end

    def find_commentable
      params.each do |name, value|
        if name =~ /(.+)_id$/
          return $1.classify.constantize.find(value)
        end
        nil
      end
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    @thing = Question.new
    @questions = Question.all
  end

  def create
    @user = User.find(session[:user_id])
    @question = @user.questions.new(question_params)
    if @question.save
      redirect_to question_path(@question)
    else
      flash[:errors] = "oopsies"
      redirect_to :back
    end
  end

  def new
    @thing = Question.new
  end

  def show
    @question = Question.find(params[:id])
    @answers = @question.answers
    @comments = @question.comments
  end

  def edit
    @question = Question.find(params[:id])
  end

  def destroy
    question = Question.find(params[:id])
    question.destroy
    redirect_to questions_path
  end

  def update
    @question = Question.find(params[:id])
    @question.update_attributes(question_params)
    redirect_to question_path
  end

  private

  def question_params
    params.require(:question).permit(:title, :content, :all_tags)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def login
    if @user = User.authenticate(user_params[:email], user_params[:password])
      session[:user_id] = @user.id
    else
      flash[:message] = "Please try again."
    end
    redirect_to root_path
  end

  def signup
    if @user = User.create(user_params)
      session[:user_id] = @user.id
      redirect_to root_path
    else
      redirect_to signup_path
    end
  end

  def logout
    session.delete(:user_id)
    redirect_to root_path
  end


  private

  def user_params
    params.require(:user).permit(:email, :first_name, :last_name, :password)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	skip_before_filter :verify_authenticity_token

	def show
		@user = User.find(params[:id]) || current_user
		@questions = Question.where(user_id: @user.id)
		@answers = Answer.where(user_id: @user.id)
	end

	def login
		@user = User.new
	end

	def new    #signup form
		@user = User.new
	end

  def answered_questions
  	user = User.find(params[:id]) || current_user
  	@answered_questions = user.answered_questions.uniq
	end

	helper_method :answered_questions
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/answers/_form.html.erb
<%= form_for(answer) do |f| %>
  <%= f.label :content %>:
  <%= f.text_area :content %><br />

  <%= f.submit %>
<% end %>

app/views/answers/edit.html.erb
<div class='content'>
	<%= form_for @answer do |f| %>
	<%= f.label :content %>:
	<%= f.text_area :content %><br />

	<%= f.submit %>
	<% end %>
</div>

app/views/answers/index.html.erb
path: /answers<br />
<br />

<ul>
	<% @answers.each do |answer| %>
	<li>
	Question: <%= link_to answer.question.title, question_path(answer.question) %><br />
	answerd by: <%= link_to answer.user.email, user_path(answer.user) %><br />
	<%= answer.content %>
	</li><br />
	<% end %>
</ul>

app/views/answers/new.html.erb
<div class='content'>
	<%= form_for @answer, url: question_answers_path do |f| %>
	<%= f.label :content %>:
	<%= f.text_area :content %><br />

	<%= f.submit %>
	<% end %>
</div>

app/views/answers/show.erb
<%= @answer.question.title %>
<%= answer.content%>

<% if current_user == @answer.user %>
<%= link_to 'Edit', edit_question_path %>
<%= link_to 'Delete', question_path, method: :delete %>
<% end %>

<!-- add 'Back' link -->

app/views/answers/show.html.erb
<%= @answer.question.title %>
<%= answer.content%>

<% if current_user == @answer.user %>
<%= link_to 'Edit', edit_question_path %>
<%= link_to 'Delete', question_path, method: :delete %>
<% end %>

<!-- add 'Back' link -->

app/views/comments/_form.html.erb
<div class='content'>
  <%= form_for [@commentable, Comment.new] do |f| %>
    <% if @comment.errors.any? %>
      <div id="error">
        <% @comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
      <%= f.label :content %><br>
      <%= f.text_area :content %>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/comments/index.html.erb
    <% @comments.each do |comment| %>
    <ul>
        <li><%= comment.content %></li>
    </ul>
    <% end %>


<br>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

app/views/layouts/_header.html.erb
<header>
	<nav>
		<ul>
				<li><a href="/">Home</a></li>
			<% if logged_in? %>
				<li><%= link_to "Log Out", logout_path, method: "delete" %></li>
				<li><%= link_to "My User Profile", user_path(current_user) %> </li>
			<% else %>
				<li><%= render 'users/login' %></li>
			<% end %>
		</ul>
	</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bison Overflow</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>

<%= yield %>

</body>
</html>

app/views/questions/_new_form.html.erb
<div class="content">
  <%= form_for(@thing) do |f| %>
    <div class="large-10 large-centered columns">
      <%= f.text_field :title, placeholder: "Question Title" %>
    </div>
    <div class="large-10 large-centered columns">
      <%= f.text_area :content, placeholder: "Your Question", rows: 5 %>
    </div>
    <div class="large-10 large-centered columns">
      <%= f.text_field :all_tags, placeholder: "Tags separated by comma" %>
    </div>
    <div class="large-10 large-centered columns">
      <%= f.submit "Post", class: "button"%>
    </div>
  <% end %>
</div>
<!-- 
row text-center -->

app/views/questions/edit.html.erb
<div class='content'>
	<%= form_for @question, url: question_path(@question) do |f| %>
	<%= f.label :title %>:
	<%= f.text_field :title %><br>

	<%= f.label :content %>
	<%= f.text_area :content %><br>

  <%= f.label :all_tags %>
  <%= f.text_area :all_tags %><br>

	<%= f.submit %>
	<% end %>
	<%= flash[:errors] %>
</div>

app/views/questions/index.html.erb
<%= render "questions/new_form" %>
<div ="questions_container">
  <ul>
  <% @questions.each do |question| %>
    <li>
    <h2><%= link_to question.title, question_path(question) %></h2>
    <%= question.content %></br>
    Tags: <%= question.all_tags %>
    </li><br/>
  <% end %>
  </ul>

app/views/questions/new.html.erb
<div class="content">
  <%= form_for @thing, url: {action: "create"} do |f| %>
    <%= f.label :title %>:
    <%= f.text_field :title %><br>

    <%= f.label :content %>
    <%= f.text_area :content %><br>

    <%= f.submit %>
  <% end %>
  <%= flash[:errors] %>
</div>

app/views/questions/show.html.erb
<div class="question">
  <h2><%= @question.title %></h2>
  <p><%= @question.content %></p>
  <p>You can come back to your question at:
    <%= link_to request.original_url, questions_path(@question) %>
    <p>Tags: <%= @question.all_tags %>
<% if current_user == @question.user %>
<%= link_to 'Edit', edit_question_path %>
<%= link_to 'Delete', question_path, method: :delete %>
<% end %>
<%= link_to 'Back', questions_path %>
<%= link_to 'Answer this question', new_question_answer_path(@question) %>
<%= link_to 'Comment', new_question_comment_path(@question) %>

<h3>Comments</h3>
<ul>
	<% @comments.each do |comment| %>
	<li><%= comment.content%></li><br>
	<% end %>
</div>

<div class='answers'>
<h3>Answers</h3>
<ul>
		<% @answers.each do |answer| %>
		<li><%= answer.content%><br />
		<br />
		by <%= link_to answer.user.full_name, user_path(answer.user) %><br />
		<br />
		<% if current_user == answer.user %>
		<%= link_to 'Edit my answer', edit_answer_path(answer) %>
		<%= link_to 'Delete my answer', answer_path, method: :delete %>
		<% end %>

		</li>
		<li>
			<%= link_to 'Comment', new_answer_comment_path(answer) %>
		</li>

	<div class='comments'>
		<h4>Comments</h4>
		<% answer.comments.each do |comment| %>
		<li><%= comment.content%></li>
		<% end %>
	</div>
		<br />
	<% end %>
</ul>
</div>

app/views/users/_login.html.erb
<!-- <h1>Login</h1> -->
<li><%= link_to 'Sign Up', signup_path %><li>
<%= form_for @user, url: '/login', action: 'post' do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited
        this user from being saved:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    <%= f.label :email %>
    <%= f.text_field :email %>

    <%= f.label :password %>
    <%= f.password_field :password, :value => '' %>
    <%= f.submit "Log in" %>
<% end %>

<%#= link_to 'Back', root_path %>

app/views/users/index.html.erb
landing page after login<br />
view: /users/index

app/views/users/login.html.erb
<h1>Login</h1>

<%= form_for @user, url: '/login', action: 'post' do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited
        this user from being saved:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label :password %><br>
    <%= f.password_field :password, :value => '' %>
  </p>

  <p>
    <%= f.submit "Log in" %>
  </p>

<% end %>
<%= link_to 'Sign Up', signup_path %>
<%= link_to 'Back', root_path %>

app/views/users/new.html.erb
<div class='content'>
  <h1>Sign Up</h1>

  <%= form_for @user, url: signup_path do |f|  %>
  <% if @user.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@user.errors.count, "error") %> prohibited
      this user from being saved:
    </h2>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div id="signup_form">
    <p>
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </p>

    <p>
      <%= f.label :first_name %><br>
      <%= f.text_field :first_name %>
    </p>

    <p>
      <%= f.label :last_name %><br>
      <%= f.text_field :last_name %>
    </p>

    <p>
      <%= f.label :password %><br>
      <%= f.password_field :password, :value => '' %>
    </p>

    <p>
      <%= f.submit "Sign up" %>
    </p>

    <% end %>
    <%= link_to 'Back', root_path %>
  </div>
</div>

app/views/users/show.html.erb
<div ="questions_container">
  <% if @user == current_user %>
  <h1>Welcome, <%= @user.first_name + " " + @user.last_name %>, here are your questions:</h1>
  <% end %>

  <h3>My questions</h3>
    <% unless @questions.length == 0 %>
  <ul>
  <% @questions.each do |question| %>
    <li>
    <h2><%= link_to question.title, question_path(question) %></h2>
    <%= question.content %>
    </li>
    </br>
    Tags: <%= question.all_tags %>
  <% end %>
  <% else %>
    <p>You have no active questions.
  <% end %>
  </ul>

  <h3>My answers</h3>
  <ul>
    <% @answers.each do |answer| %>
    <li><%= answer.content %><br />
    <%= link_to 'Go to the question', question_path(answer.question) %>
    </li>
    <br />
    <% end %>
  </ul>

  <h3>All Questions I've answered</h3>
  <ul>
    <% answered_questions.each do |question| %>
    <li><%= link_to question.title, question_path(question) %> by <%= link_to question.user.full_name, user_path %>
    </li>
    <br />
    <% end %>
  </ul>